# Generated by Django 4.1.7 on 2023-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=100, unique=True)),
                ('albumArtist', models.CharField(max_length=100)),
                ('albumRealeaseYear', models.CharField(max_length=100)),
                ('albumCover', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardName', models.CharField(max_length=100, unique=True)),
                ('dateOfAward', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=100, unique=True)),
                ('songDuration', models.CharField(max_length=100)),
            ],
        ),
    ]
