# Generated by Django 4.1.7 on 2023-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_songname_song_songtitle_album_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='awards',
            field=models.ManyToManyField(related_name='albums', to='catalog.awards'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', to='catalog.song'),
        ),
    ]
